define([
    "./columnchart",
    "./piechart",
    "./polarchart",
    "./ringchart",
    "./scatterchart",
    "./splinechart",
    "./tschart",
    "./waterfallchart",
    "./matrixchart",
    "./bubblechart",
    "./areachart",
    "./utils/utils"
],function(ColumnChart,PieChart,PolarChart,RingChart,ScatterChart,SplineChart,TsChart,WaterfallChart,MatrixChart,BubbleChart,AreaChart,utils){
	return {
		ColumnChart:ColumnChart,
		PieChart:PieChart,
		PolarChart:PolarChart,
		RingChart:RingChart,
		ScatterChart:ScatterChart,
		SplineChart:SplineChart,
		TsChart:TsChart,
		WaterfallChart:WaterfallChart,
		MatrixChart:MatrixChart,
		BubbleChart:BubbleChart,
		AreaChart:AreaChart,
		utils:utils
	}
});