define([
    "./columnchart",
    "./piechart",
    "./polarchart",
    "./ringchart",
    "./scatterchart",
    "./splinechart",
    "./tschart",
    "./waterfallchart",
    "./matrixchart"
],function(ColumnChart,PieChart,PolarChart,RingChart,ScatterChart,SplineChart,TsChart,WaterfallChart,MatrixChart){
	return {
		ColumnChart:ColumnChart,
		PieChart:PieChart,
		PolarChart:PolarChart,
		RingChart:RingChart,
		ScatterChart:ScatterChart,
		SplineChart:SplineChart,
		TsChart:TsChart,
		WaterfallChart:WaterfallChart,
		MatrixChart:MatrixChart
	}
});